# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'match-app.ui'
#
# Created: Thu Jun 25 17:47:12 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 679)
        MainWindow.setMinimumSize(QtCore.QSize(0, 500))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setMargin(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.topframe = QtGui.QFrame(self.centralwidget)
        self.topframe.setMinimumSize(QtCore.QSize(0, 326))
        self.topframe.setFrameShape(QtGui.QFrame.StyledPanel)
        self.topframe.setFrameShadow(QtGui.QFrame.Raised)
        self.topframe.setObjectName("topframe")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.topframe)
        self.verticalLayout_5.setMargin(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.centerframe = QtGui.QFrame(self.topframe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centerframe.sizePolicy().hasHeightForWidth())
        self.centerframe.setSizePolicy(sizePolicy)
        self.centerframe.setMaximumSize(QtCore.QSize(16777215, 306))
        self.centerframe.setFrameShape(QtGui.QFrame.Panel)
        self.centerframe.setFrameShadow(QtGui.QFrame.Raised)
        self.centerframe.setObjectName("centerframe")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centerframe)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtGui.QFrame(self.centerframe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 286))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtGui.QLabel(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.selectedImageLabel = QtGui.QLabel(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedImageLabel.sizePolicy().hasHeightForWidth())
        self.selectedImageLabel.setSizePolicy(sizePolicy)
        self.selectedImageLabel.setMinimumSize(QtCore.QSize(200, 200))
        self.selectedImageLabel.setMaximumSize(QtCore.QSize(200, 200))
        self.selectedImageLabel.setBaseSize(QtCore.QSize(200, 200))
        self.selectedImageLabel.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.selectedImageLabel.setScaledContents(True)
        self.selectedImageLabel.setObjectName("selectedImageLabel")
        self.verticalLayout_3.addWidget(self.selectedImageLabel)
        self.label_4 = QtGui.QLabel(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.directory_lineEdit = QtGui.QLineEdit(self.frame_4)
        self.directory_lineEdit.setReadOnly(True)
        self.directory_lineEdit.setObjectName("directory_lineEdit")
        self.verticalLayout_3.addWidget(self.directory_lineEdit)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_3 = QtGui.QFrame(self.centerframe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_3.setBaseSize(QtCore.QSize(31, 0))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.loadImageButton = QtGui.QPushButton(self.frame_3)
        self.loadImageButton.setGeometry(QtCore.QRect(70, 50, 75, 23))
        self.loadImageButton.setObjectName("loadImageButton")
        self.selectDirButton = QtGui.QPushButton(self.frame_3)
        self.selectDirButton.setGeometry(QtCore.QRect(70, 80, 75, 23))
        self.selectDirButton.setObjectName("selectDirButton")
        self.matchButton = QtGui.QPushButton(self.frame_3)
        self.matchButton.setGeometry(QtCore.QRect(70, 180, 75, 23))
        self.matchButton.setObjectName("matchButton")
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_2 = QtGui.QFrame(self.centerframe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(220, 0))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 257, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.matchImageLabel = QtGui.QLabel(self.frame_2)
        self.matchImageLabel.setGeometry(QtCore.QRect(10, 30, 200, 200))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matchImageLabel.sizePolicy().hasHeightForWidth())
        self.matchImageLabel.setSizePolicy(sizePolicy)
        self.matchImageLabel.setMinimumSize(QtCore.QSize(200, 200))
        self.matchImageLabel.setMaximumSize(QtCore.QSize(200, 200))
        self.matchImageLabel.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.matchImageLabel.setScaledContents(True)
        self.matchImageLabel.setObjectName("matchImageLabel")
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout_5.addWidget(self.centerframe)
        self.verticalLayout_2.addWidget(self.topframe)
        self.bottomframe = QtGui.QFrame(self.centralwidget)
        self.bottomframe.setFrameShape(QtGui.QFrame.StyledPanel)
        self.bottomframe.setFrameShadow(QtGui.QFrame.Raised)
        self.bottomframe.setObjectName("bottomframe")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.bottomframe)
        self.verticalLayout_4.setMargin(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.logframe = QtGui.QFrame(self.bottomframe)
        self.logframe.setAutoFillBackground(False)
        self.logframe.setFrameShape(QtGui.QFrame.Panel)
        self.logframe.setFrameShadow(QtGui.QFrame.Raised)
        self.logframe.setLineWidth(1)
        self.logframe.setObjectName("logframe")
        self.verticalLayout = QtGui.QVBoxLayout(self.logframe)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtGui.QLabel(self.logframe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.textBrowser = QtGui.QTextBrowser(self.logframe)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowser.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.verticalLayout_4.addWidget(self.logframe)
        self.verticalLayout_2.addWidget(self.bottomframe)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Selected Image", None, QtGui.QApplication.UnicodeUTF8))
        self.selectedImageLabel.setText(QtGui.QApplication.translate("MainWindow", "selected image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.loadImageButton.setText(QtGui.QApplication.translate("MainWindow", "Load Image", None, QtGui.QApplication.UnicodeUTF8))
        self.selectDirButton.setText(QtGui.QApplication.translate("MainWindow", "Select dir", None, QtGui.QApplication.UnicodeUTF8))
        self.matchButton.setText(QtGui.QApplication.translate("MainWindow", "Match", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Matched Image", None, QtGui.QApplication.UnicodeUTF8))
        self.matchImageLabel.setText(QtGui.QApplication.translate("MainWindow", "match image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))

