# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'util_app.ui'
#
# Created: Tue Apr 28 23:39:14 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 490)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.toolBox.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox.setLineWidth(1)
        self.toolBox.setObjectName("toolBox")
        self.page_1 = QtGui.QWidget()
        self.page_1.setGeometry(QtCore.QRect(0, 0, 570, 268))
        self.page_1.setObjectName("page_1")
        self.lineEdit = QtGui.QLineEdit(self.page_1)
        self.lineEdit.setGeometry(QtCore.QRect(50, 60, 500, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtGui.QLabel(self.page_1)
        self.label.setGeometry(QtCore.QRect(10, 60, 31, 16))
        self.label.setObjectName("label")
        self.downloadButton = QtGui.QPushButton(self.page_1)
        self.downloadButton.setGeometry(QtCore.QRect(470, 90, 75, 23))
        self.downloadButton.setObjectName("downloadButton")
        self.label_3 = QtGui.QLabel(self.page_1)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 31, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtGui.QLabel(self.page_1)
        self.label_5.setGeometry(QtCore.QRect(120, 30, 21, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtGui.QLineEdit(self.page_1)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 30, 40, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtGui.QLineEdit(self.page_1)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 30, 40, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtGui.QLabel(self.page_1)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 31, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtGui.QLineEdit(self.page_1)
        self.lineEdit_4.setGeometry(QtCore.QRect(50, 0, 41, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.toolBox.addItem(self.page_1, "")
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 570, 268))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 570, 268))
        self.page_3.setObjectName("page_3")
        self.label_7 = QtGui.QLabel(self.page_3)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 31, 16))
        self.label_7.setObjectName("label_7")
        self.norm_prefix_lineEdit = QtGui.QLineEdit(self.page_3)
        self.norm_prefix_lineEdit.setGeometry(QtCore.QRect(50, 0, 51, 20))
        self.norm_prefix_lineEdit.setObjectName("norm_prefix_lineEdit")
        self.norm_size_lineEdit = QtGui.QLineEdit(self.page_3)
        self.norm_size_lineEdit.setGeometry(QtCore.QRect(50, 30, 51, 20))
        self.norm_size_lineEdit.setObjectName("norm_size_lineEdit")
        self.label_8 = QtGui.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 31, 16))
        self.label_8.setObjectName("label_8")
        self.norm_log_textedit = QtGui.QPlainTextEdit(self.page_3)
        self.norm_log_textedit.setGeometry(QtCore.QRect(190, 0, 371, 171))
        self.norm_log_textedit.setReadOnly(False)
        self.norm_log_textedit.setObjectName("norm_log_textedit")
        self.label_9 = QtGui.QLabel(self.page_3)
        self.label_9.setGeometry(QtCore.QRect(160, 0, 31, 16))
        self.label_9.setObjectName("label_9")
        self.normalizeButton = QtGui.QPushButton(self.page_3)
        self.normalizeButton.setGeometry(QtCore.QRect(30, 60, 75, 23))
        self.normalizeButton.setObjectName("normalizeButton")
        self.line = QtGui.QFrame(self.page_3)
        self.line.setGeometry(QtCore.QRect(140, 0, 20, 201))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.resize_size_lineEdit = QtGui.QLineEdit(self.page_4)
        self.resize_size_lineEdit.setGeometry(QtCore.QRect(310, 30, 51, 20))
        self.resize_size_lineEdit.setObjectName("resize_size_lineEdit")
        self.label_10 = QtGui.QLabel(self.page_4)
        self.label_10.setGeometry(QtCore.QRect(280, 30, 31, 16))
        self.label_10.setObjectName("label_10")
        self.resizeButton = QtGui.QPushButton(self.page_4)
        self.resizeButton.setGeometry(QtCore.QRect(370, 30, 75, 23))
        self.resizeButton.setObjectName("resizeButton")
        self.label_11 = QtGui.QLabel(self.page_4)
        self.label_11.setGeometry(QtCore.QRect(10, 0, 51, 16))
        self.label_11.setObjectName("label_11")
        self.resize_basedirectory_lineEdit = QtGui.QLineEdit(self.page_4)
        self.resize_basedirectory_lineEdit.setGeometry(QtCore.QRect(70, 0, 491, 20))
        self.resize_basedirectory_lineEdit.setObjectName("resize_basedirectory_lineEdit")
        self.listWidget = QtGui.QListWidget(self.page_4)
        self.listWidget.setGeometry(QtCore.QRect(10, 30, 256, 192))
        self.listWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        self.toolBox.addItem(self.page_4, "")
        self.verticalLayout.addWidget(self.toolBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 590, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Util Application", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Download images, detect faces, normalize cropped images, resize images", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "URL:", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadButton.setText(QtGui.QApplication.translate("MainWindow", "Download!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Start:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "End:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Prefix:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_1), QtGui.QApplication.translate("MainWindow", "Download Images", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("MainWindow", "Detect Faces", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Prefix:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Log:", None, QtGui.QApplication.UnicodeUTF8))
        self.normalizeButton.setText(QtGui.QApplication.translate("MainWindow", "Normalize", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QtGui.QApplication.translate("MainWindow", "Normalize Cropped Images", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.resizeButton.setText(QtGui.QApplication.translate("MainWindow", "Resize", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), QtGui.QApplication.translate("MainWindow", "Resize Images", None, QtGui.QApplication.UnicodeUTF8))

